animals_shelter/animals/urls.py
from django.urls import path
from . import views

app_name = 'animals'
urlpatterns = [
    path('', views.animals_list, name='animals_list'),
    path('add_animal/', views.add_new_animal, name='add_animal'),
    path('<int:animal_id>/animal_edit/', views.animal_edit, name='animal_edit'),
    path('<int:animal_id>/animal_delete/', views.animal_delete, name='animal_delete'),

]

animals_shelter/animals_shelter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animals.urls', namespace='animals')),
]

animals_shelter/animals/models.py
from django.db import models
from django.core.validators import MaxValueValidator, RegexValidator
from django.core.exceptions import ValidationError


def validate_date(value):
    year = value.year
    if year < 1900 or year > 2023:
        raise ValidationError('Введіть коректний рік народження.')


def validate_name(value):
    if not value.isalpha():
        raise ValidationError('Кличка повинна містити тільки букви')


class Animal(models.Model):
    ANIMAL_TYPES = [
        ('Кіт', 'Кіт'),
        ('Пес', 'Пес'),
        ('Птичка', 'Птичка'),
        ('Єнот', 'Єнот'),
        ('Черепаха', 'Черепаха'),

    ]
    entry_date = models.DateTimeField(auto_now=True)
    pet_type = models.CharField(max_length=20, verbose_name='Тип тваринки', choices=ANIMAL_TYPES)
    pet_name = models.CharField(validators=[validate_name], max_length=25, verbose_name='Кличка')
    pet_birthday = models.DateField(validators=[validate_date], verbose_name='День народження')
    pet_age = models.PositiveIntegerField(
        validators=[MaxValueValidator(150, message='Введіть коректний вік в повних роках')], verbose_name='Вік')
    pet_height = models.PositiveIntegerField(
        validators=[MaxValueValidator(150, message='Введіть коректний зріст в см')], verbose_name='Зріст')
    pet_weight = models.DecimalField(max_digits=7, decimal_places=2,
                                     validators=[MaxValueValidator(150, message='Введіть коректну вагу в кг')],
                                     verbose_name='Вага')
    pet_passport = models.CharField(
        validators=[RegexValidator(r'[A-Z]{2}\d{6}', message='Коректний формат: АА123456')],
        max_length=8, blank=True, null=True, verbose_name='Паспорт')

    def __str__(self):
        return self.pet_type, self.pet_passport

    class Meta:
        verbose_name = 'Animal'
        verbose_name_plural = 'Animals'

animals_shelter/animals/forms.py
from django import forms
from .models import Animal


class AnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = '__all__'
        widgets = {
            'pet_birthday': forms.DateInput(attrs={'type': 'date'}),
        }

animals_shelter/animals/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Animal
from .forms import AnimalForm

HOME_PAGE = 'animals:animals_list'


def animals_list(request):
    animals = Animal.objects.all()
    animal_type = request.GET.get('pet_type')
    sort_by = request.GET.get('sort_by', 'id')

    if animal_type:
        animals = Animal.objects.filter(pet_type=animal_type)

    if sort_by:
        animals = animals.order_by(sort_by)

    return render(request, 'animals/animals_list.html', {
        'animals': animals,
        'sort_by': sort_by
    })


def add_new_animal(request):
    if request.method == 'POST':
        form = AnimalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(HOME_PAGE)
    else:
        form = AnimalForm()
    return render(request, 'animals/add_animal.html', {'form': form})


def animal_edit(request, animal_id):
    animal = get_object_or_404(Animal, id=animal_id)

    if request.method == 'POST':
        form = AnimalForm(request.POST, instance=animal)
        if form.is_valid():
            form.save()
            return redirect(HOME_PAGE)
    else:
        form = AnimalForm(instance=animal)

    return render(request, 'animals/animal_edit.html', {'form': form, 'animal': animal})


def animal_delete(request, animal_id):
    animal = get_object_or_404(Animal, id=animal_id)

    if request.method == 'POST':
        animal.delete()
        return redirect(HOME_PAGE)

    return render(request, 'animals/animal_delete.html', {'animal': animal})

animals_shelter/templates/animals/add_animal.html
{% extends 'base.html' %}

{% block content %}

<h2>Додати тваринку</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Додати</button>
</form>

{% endblock %}

animals_shelter/templates/animals/animal_delete.html
{% extends 'base.html' %}

{% block content %}

<h2>Видалити тваринку</h2>

<p>Ви справді хочете видалити запис про "{{ animal.pet_name }}" ?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Видалити...</button>
</form>

{% endblock %}

animals_shelter/templates/animals/animal_edit.html
{% extends 'base.html' %}

{% block content %}
<h2>Змінити дані тваринки</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберегти</button>
</form>
{% endblock %}

animals_shelter/templates/animals/animals_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Список тваринок</h2>

<!-- Фільтр по типу тварини -->
<form method="get" action="{% url 'animals:animals_list' %}">
    <label for="animal-type-filter">Відфільтрувати по типу:</label>
    <select name="pet_type" id="animal-type-filter">

        <option value="">Всі</option>
        <option value="Кіт">Коти</option>
        <option value="Пес">Собаки</option>
        <option value="Птичка">Птиці</option>
        <option value="Єнот">Єноти</option>
        <option value="Черепаха">Черепахи</option>

    </select>
    <button type="submit">Застосувати</button>
</form>
<br>

{% if animals %}
<table border="1">
    <thead>
    <tr>
        <!-- Заголовки з сортування за зростанням та спаданням -->
        <th>
            <a href="{% url 'animals:animals_list' %}?sort_by=pet_type">↑</a>
            Тип
            <a href="{% url 'animals:animals_list' %}?sort_by=-pet_type">↓</a>
        </th>
        <th>
            <a href="{% url 'animals:animals_list' %}?sort_by=pet_name">↑</a>
            Кличка
            <a href="{% url 'animals:animals_list' %}?sort_by=-pet_name">↓</a>
        </th>
        <th>
            <a href="{% url 'animals:animals_list' %}?sort_by=pet_birthday">↑</a>
            Дата народження
            <a href="{% url 'animals:animals_list' %}?sort_by=-pet_birthday">↓</a>
        </th>
        <th>
            <a href="{% url 'animals:animals_list' %}?sort_by=pet_age">↑</a>
            Вік
            <a href="{% url 'animals:animals_list' %}?sort_by=-pet_age">↓</a>
        </th>
        <th>
            <a href="{% url 'animals:animals_list' %}?sort_by=pet_height">↑</a>
            Зріст
            <a href="{% url 'animals:animals_list' %}?sort_by=-pet_height">↓</a>
        </th>
        <th>
            <a href="{% url 'animals:animals_list' %}?sort_by=pet_weight">↑</a>
            Вага
            <a href="{% url 'animals:animals_list' %}?sort_by=-pet_weight">↓</a>
        </th>
        <th>Паспорт</th>

    </tr>
    </thead>
    <tbody>
    {% for animal in animals %}
    <tr>
        <td>{{ animal.pet_type }}</td>
        <td>{{ animal.pet_name}}</td>
        <td>{{ animal.pet_birthday|date:"d.m.Y" }}</td>
        <td>{{ animal.pet_age }}</td>
        <td>{{ animal.pet_height }}</td>
        <td>{{ animal.pet_weight }}</td>
        {% if animal.pet_passport %}
        <td>{{ animal.pet_passport }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        <td><a href="{% url 'animals:animal_edit' animal_id=animal.id %}">Редагувати</a></td>
        <td><a href="{% url 'animals:animal_delete' animal_id=animal.id %}">Видалити</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h2>Всі тваринки знайшли своїх власників!</h2>

{% endif %}

{% endblock %}

animals_shelter/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Animals Shelter</title>

</head>
<body>
<h1>O_R Shelter</h1>
<a href="{% url 'animals:animals_list' %}">Головна</a>
<a href="{% url 'animals:add_animal' %}">Додати тваринку</a>
{% block content %}

{% endblock %}
</body>
</html>